// <auto-generated />
using System;
using IzmirBel.Survey.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IzmirBel.Survey.Migrations
{
    [DbContext(typeof(SurveyDbContext))]
    partial class SurveyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IzmirBel.Survey.Models.CustomerSurvey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SurveyCompleteMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomerSurveys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9900"),
                            SurveyCompleteMessage = "You completed the survey, THANKS!!!",
                            Title = "Staff Survey - İzmir Metropolitan Municipality"
                        });
                });

            modelBuilder.Entity("IzmirBel.Survey.Models.CustomerSurveyResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("CustomerSurveysResponses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8cd6f82-50f1-4ebf-95c3-4fd1956d62f5"),
                            SurveyId = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9900")
                        },
                        new
                        {
                            Id = new Guid("31470369-f098-4ab8-8e0c-bf98134c61a9"),
                            SurveyId = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9900")
                        });
                });

            modelBuilder.Entity("IzmirBel.Survey.Models.SurveyAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SurveyResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SurveyResponseId");

                    b.ToTable("SurveyAnswer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7724ce32-427d-46d5-8033-07a8756083eb"),
                            Answer = "Less than 1 year",
                            Question = "How long have you worked at İzmir Metropolitan Municipality?",
                            SurveyResponseId = new Guid("d8cd6f82-50f1-4ebf-95c3-4fd1956d62f5")
                        },
                        new
                        {
                            Id = new Guid("9cbaa84f-a1b2-4557-9b0a-8f16e615c1b6"),
                            Answer = "Yes",
                            Question = "Do you enjoy working at İzmir Metropolitan Municipality?",
                            SurveyResponseId = new Guid("d8cd6f82-50f1-4ebf-95c3-4fd1956d62f5")
                        },
                        new
                        {
                            Id = new Guid("3e67aa19-0fe2-4a84-85d6-1844be9d7a8f"),
                            Answer = "It's really cool here!",
                            Question = "Any comments on how you find working for İzmir Metropolitan Municipality?",
                            SurveyResponseId = new Guid("d8cd6f82-50f1-4ebf-95c3-4fd1956d62f5")
                        },
                        new
                        {
                            Id = new Guid("5bc2f91e-dcd3-481e-9712-8794431b6f97"),
                            Answer = "More than 5 years",
                            Question = "How long have you worked at İzmir Metropolitan Municipality?",
                            SurveyResponseId = new Guid("31470369-f098-4ab8-8e0c-bf98134c61a9")
                        },
                        new
                        {
                            Id = new Guid("1f970bf1-3c5d-4a6a-94ec-77adb79d84a9"),
                            Answer = "No",
                            Question = "Do you enjoy working at İzmir Metropolitan Municipality?",
                            SurveyResponseId = new Guid("31470369-f098-4ab8-8e0c-bf98134c61a9")
                        },
                        new
                        {
                            Id = new Guid("e8a13a1e-42d2-4608-bd8e-de3a916d12a3"),
                            Answer = "My computer is really slow",
                            Question = "Any comments on how you find working for İzmir Metropolitan Municipality?",
                            SurveyResponseId = new Guid("31470369-f098-4ab8-8e0c-bf98134c61a9")
                        });
                });

            modelBuilder.Entity("IzmirBel.Survey.Models.SurveyQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PossibleAnswers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("SurveyQuestions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9901"),
                            Answer = "",
                            PossibleAnswers = "Less than 1 year|1-5 years|More than 5 years",
                            Question = "How long have you worked at İzmir Metropolitan Municipality?",
                            SurveyId = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9900")
                        },
                        new
                        {
                            Id = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9902"),
                            Answer = "",
                            PossibleAnswers = "Yes|No|Sometimes",
                            Question = "Do you enjoy working at İzmir Metropolitan Municipality?",
                            SurveyId = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9900")
                        },
                        new
                        {
                            Id = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9903"),
                            Answer = "",
                            PossibleAnswers = "",
                            Question = "Any comments on how you find working for İzmir Metropolitan Municipality?",
                            SurveyId = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9900")
                        });
                });

            modelBuilder.Entity("IzmirBel.Survey.Models.SurveyAnswer", b =>
                {
                    b.HasOne("IzmirBel.Survey.Models.CustomerSurveyResponse", "SurveyResponse")
                        .WithMany("Answers")
                        .HasForeignKey("SurveyResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyResponse");
                });

            modelBuilder.Entity("IzmirBel.Survey.Models.SurveyQuestion", b =>
                {
                    b.HasOne("IzmirBel.Survey.Models.CustomerSurvey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("IzmirBel.Survey.Models.CustomerSurvey", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("IzmirBel.Survey.Models.CustomerSurveyResponse", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
